CREATE DATABASE app
GO

USE app
GO

DROP TABLE message_lib
DROP TABLE threads
DROP TABLE users

CREATE TABLE users(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	email VARCHAR(50) NOT NULL UNIQUE,
	username VARCHAR(50) NOT NULL UNIQUE,
	pwd VARCHAR(50) NOT NULL,
	link_avt VARBINARY(100),
	chanel_name VARCHAR(255) NOT NULL UNIQUE,
	birthday DATE NOT NULL,
	subcriber INT DEFAULT 0
)
GO


CREATE TABLE threads(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	cr_date DATETIME NOT NULL DEFAULT GETDATE(),
	fk_idSend INT FOREIGN KEY REFERENCES users(id),
	fk_idRecieve INT FOREIGN KEY REFERENCES users(id)
)
GO


CREATE TABLE message_lib(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	content nTEXT NOT NULL,
	cr_date DATETIME NOT NULL DEFAULT GETDATE(),
	fk_idThread INT FOREIGN KEY REFERENCES threads(id),
	fk_idUser INT FOREIGN KEY REFERENCES users(id),
	isSeen BIT DEFAULT 0
)
GO

ALTER TABLE users
ALTER COLUMN link_avt VARBINARY(MAX)


